version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker  # Define o ambiente de execução da API
      - ConnectionStrings__MysqlConnection=Server=db;Database=DB_Bank;Uid=dev;Pwd=senhaforte1;
    depends_on:
      - db
    networks:
      - bank-network

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "senhaforteroot"
      MYSQL_DATABASE: "DB_Bank"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "senhaforte1"
    networks:
      - bank-network

networks:
  bank-network:
