version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - bank-network

  api:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8443:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__MysqlConnection: "Server=db;Database=DB_Bank;Uid=dev;Pwd=senhaforte1;"
    depends_on:
      - db
    networks:
      - bank-network
    restart: on-failure

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - bank-network
    restart: on-failure

  prometheus:
    build:
      context: prometheus
      dockerfile: Dockerfile
    ports: 
      - "9090:9090"
    networks:
      - bank-network
    restart: on-failure

networks:
  bank-network:
    driver: bridge
