version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "44392:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__MysqlConnection: "Server=db;Database=DB_Bank;Uid=dev;Pwd=senhaforte1;"
    depends_on:
      - db
    networks:
      - bank-network

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "senhaforteroot"
      MYSQL_DATABASE: "DB_Bank"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "senhaforte1"
    networks:
      - bank-network

networks:
  bank-network:
