version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - bank-network

  api:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "44392:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - db
    networks:
      - bank-network

networks:
  bank-network:
